### ISSUE TITLE
Visual Studio Code ?

### ISSUE THREAD

**Issue by ghost** [codeinthedark/awesome-power-mode#11]
http://code.visualstudio.com

**Comment by ghost** [comment]
+1

**Comment by Xstoudi** [comment]
Definitely need it !

**Comment by martingrondein** [comment]
+1

**Comment by braianjansen** [comment]
+1

**Comment by graduenz** [comment]
+1

**Comment by mumbast** [comment]
+1

**Comment by willin** [comment]
+1

**Comment by alejandrocoding** [comment]
+1

**Comment by Binaryify** [comment]
+1

**Comment by oultrox** [comment]
Please! +1

**Comment by haroldduan** [comment]
come on +1

**Comment by OSIMLY** [comment]
+1

**Comment by Varun-Sethu** [comment]
+1

**Comment by hoovercj** [comment]
https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-power-mode

**Comment by willin** [comment]
@hoovercj chinese support is not so friendly

**Comment by haroldduan** [comment]
@hoovercj  Thanks

**Comment by hoovercj** [comment]
There's a new version out now. I haven't had a chance to test Chinese yet, but the visuals are much better.

![image](https://github.com/hoovercj/vscode-power-mode/blob/7b00dab2fe01ed7eed8fc4ba8536141d314680b8/images/demo.gif?raw=true)

**Comment by haroldduan** [comment]
I get the lastest version and reload my vs code,just now!
Awesome!
Thanks!

**Comment by Binaryify** [comment]
@hoovercj 
Really cool!
