### ISSUE TITLE
Add Emacs Support!

### ISSUE THREAD

**Issue by ItsNilDev** [codeinthedark/awesome-power-mode#22]
We want emacs support!

**Comment by elizagamedev** [comment]
[You're in luck, by a twist of fate I just finished working on a package for this.](https://github.com/elizagamedev/power-mode.el)

**Comment by ItsNilDev** [comment]
Nice!

**Comment by ItsNilDev** [comment]
So I think this should be closed now

**Comment by redblobgames** [comment]
Should be in the list :-)
